server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/UserService
    username: root
    password: Satya@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"        # expose all actuator endpoints
      base-path: /actuator  # base path for actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    eureka:
      enabled: true